# Usefull colors for menu items
    # "color: #ff7e73;
    # "color: #abe5b1;
    # "color: #abe0e5;
    # "color: #ffc873;
    # "color: #e5c6ab;
    # "color: #b8abe5; 

# ################### Menu ###################
[[main]]
identifier = "start_here"
pre = "fa fa-drafting-compass"
post = ""
name = "Start Here"
url = "/start-here"
title = ""
weight = 2


[[main]]
identifier = "view"
pre = "fa fa-th-large"
post = ""
name = "View"
url = ""
title = ""
weight = 3

[[main]]
identifier = "list_view"
pre = "fa fa-list"
post = "Post list view of all posts"
name = "List View →"
url = "/posts/"
title = ""
weight = 4
parent = "view"
[main.params]
  color = "#ff7e73"

[[main]]
identifier = "grid_view"
pre = "fa fa-th"
post = "Post grid view of all posts"
name = "Grid View →"
url = "/portfolio/"
title = ""
weight = 5
parent = "view"
[main.params]
  color = "#abe5b1"

[[main]]
identifier = "post_view_sidebar"
pre = "fa fa-file-text-o"
post = "Single post view with sidebar"
name = "Single Post View With Sidebar"
url = "/post-with-sidebar/"
title = ""
weight = 6
parent = "view"
[main.params]
  color = "#ffc873"

[[main]]
identifier = "post_view_no_sidebar"
pre = "fa fa-file-text-o"
post = "Single post view without sidebar"
name = "Single Post View Without Sidebar"
url = "/post-without-sidebar/"
title = ""
weight = 7
parent = "view"
[main.params]
  color = "#ffc873"

[[main]]
identifier = "post_view_cover"
pre = "fa fa-picture-o"
post = "Single post view with cover image"
name = "Single Post View with Cover"
url = "/post-with-cover-image/"
title = ""
weight = 8
parent = "view"
[main.params]
  color = "#abe0e5"

[[main]]
identifier = "video_post"
pre = "fa fa-film"
post = "Single post view of video post"
name = "Video Post"
url = "/video-post-view/"
title = ""
weight = 9
parent = "view"
[main.params]
  color = "#abe0e5"

[[main]]
identifier = "landinpage"
pre = "fa fa-star text-warning"
post = "Insert html on index.md file"
name = "Landing Page"
url = "/landingpage/"
title = ""
weight = 10
parent = "view"
[main.params]
  color = ""
  bordertop = true

# [[main]]
# identifier = "books"
# pre = ""
# post = ""
# name = "Books"
# url = "/books"
# title = ""
# weight = 11

[[main]]
identifier = "contact"
pre = ""
post = ""
name = "Contact"
url = "/contact/"
title = ""
weight = 12

[[main]]
identifier = "about"
pre = ""
post = ""
name = "About "
url = "/about/"
title = ""
weight = 13

# [[menu.main]]
# identifier = "more"
# pre = ""
# post = ""
# name = "More"
# url = "/more/"
# title = ""
# weight = 10

# [[menu.main]]
# identifier = "python_newsletter"
# pre = ""
# post = ""
# name = "Python Newsletter"
# url = "/more/"
# title = ""
# weight = 11
# parent = "more"

# [[menu.main]]
# identifier = "python_podcast"
# pre = ""
# post = ""
# name = "Python Podcast"
# url = "/more/"
# title = ""
# weight = 11
# parent = "more"

# [[menu.main]]
# identifier = "python_job_board"
# pre = ""
# post = ""
# name = "Python Job Board →"
# url = "/more/"
# title = ""
# weight = 12
# parent = "more"


############################## Footer ##############################
[[footer]]
  name = "Contact"
  url = "/contact"
  weight = 1

[[footer]]
  name = "RSS Feed"
  url = "/index.xml"
  weight = 2

[[footer]]
  name = "Privacy&Policy"
  url = "/privacy&policy"
  weight = 3
